# Real-Time Gaming Intelligence Platform Data Product
# Auto-generated by Implementation Agent

resource "confluent_kafka_topic" "gaming_real_time_gaming_intelligence_platform" {
  kafka_cluster {
    id = confluent_kafka_cluster.datagen_cluster.id
  }

  rest_endpoint = confluent_kafka_cluster.datagen_cluster.rest_endpoint

  topic_name       = "gaming.real-time-gaming-intelligence-platform"
  partitions_count = 6

  config = {
    "cleanup.policy" = "delete"
    "retention.ms"   = "604800000"
  }

  credentials {
    key    = confluent_api_key.cluster_admin_api_key.id
    secret = confluent_api_key.cluster_admin_api_key.secret
  }
}

