# Real-Time Customer Behavior Intelligence Data Product
# Auto-generated by Implementation Agent

resource "confluent_kafka_topic" "web_analytics_real_time_customer_behavior_intelligence" {
  kafka_cluster {
    id = confluent_kafka_cluster.datagen_cluster.id
  }

  rest_endpoint = confluent_kafka_cluster.datagen_cluster.rest_endpoint

  topic_name       = "web_analytics.real-time-customer-behavior-intelligence"
  partitions_count = 6

  config = {
    "cleanup.policy" = "delete"
    "retention.ms"   = "604800000"
  }

  credentials {
    key    = confluent_api_key.cluster_admin_api_key.id
    secret = confluent_api_key.cluster_admin_api_key.secret
  }
}

